// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrj9V67Er1rGiAimDDJFGuFAA62G4t34Y',
    appId: '1:162019669756:web:0cc0f80a3c1a9634b0c979',
    messagingSenderId: '162019669756',
    projectId: 'blog-36e2b',
    authDomain: 'blog-36e2b.firebaseapp.com',
    storageBucket: 'blog-36e2b.appspot.com',
    measurementId: 'G-RCLX9LHVT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVHU9FDmD3kWhIqb9PoHAoKTMnop0lTpc',
    appId: '1:162019669756:android:1aa56380f311ea6bb0c979',
    messagingSenderId: '162019669756',
    projectId: 'blog-36e2b',
    storageBucket: 'blog-36e2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhjgy7PxQY0cPgNL57Kno-qhkT2F8dQhs',
    appId: '1:162019669756:ios:4b29393c066b8f22b0c979',
    messagingSenderId: '162019669756',
    projectId: 'blog-36e2b',
    storageBucket: 'blog-36e2b.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhjgy7PxQY0cPgNL57Kno-qhkT2F8dQhs',
    appId: '1:162019669756:ios:e1c4d3ad281040a4b0c979',
    messagingSenderId: '162019669756',
    projectId: 'blog-36e2b',
    storageBucket: 'blog-36e2b.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
